name: Test
on:
  push:
    branches: [master]
    paths:
      - src/**
      - test/**
      - "*.json"
      - "*.ts"
      - .github/workflows/test.yml
  pull_request:
    branches: [master]
    paths:
      - src/**
      - test/**
      - "*.json"
      - "*.ts"
      - .github/workflows/test.yml
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    strategy:
      matrix:
        node-version: ["16", "18", "20"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
